### ISSUE TITLE
[BUG] - Broken markdown 

### ISSUE THREAD

**Issue by Kira272921** [App-Choreography/Best-App-Tutorials-3#6]
Hey 👋,
There is broken markdown in `Beginner Tutorials` markdown table
I guess it is the issue with the `markdown parser` of github and that of github pages 

> You could add the below setting in the `_config.yml` file to fix this issue : 
```code
markdown: GFM
```

**Comment by CodingSpecies** [comment]
@Kira272921 Thank you for pointing this issue out!
Yes, I noticed the broken table too, but didn't know how to configure it then.
Yes, soon I will create an _config.yml file and add the details soon. Thank you so much.

**Comment by Kira272921** [comment]
> @Kira272921 Thank you for pointing this issue out! Yes, I noticed the broken table too, but didn't know how to configure it then. Yes, soon I will create an _config.yml file and add the details soon. Thank you so much.

Hey I guess there is a `_config.yml` [file](https://github.com/App-Choreography/Best-App-Tutorials-3/blob/84b9fff79b9435e6be72d6942a8f7b62823e7916/_config.yml) already I guess.

Just add a new line with the content and it will be fixed.
```
markdown: GFM
```

**Comment by CodingSpecies** [comment]
@Kira272921 now the beginner tutorial table is sorted! Thank you so much for this suggestion and fix! 🎉
